portfolio/urls.py
from django.urls import path
from portfolio import views

app_name = 'me'
urlpatterns = [
    path('', views.portfolio, name='home'),
    path('about_me', views.portfolio, name='about_me'),
    path('curriculum_vitae', views.cv, name='curriculum_vitae'),
    path('contact', views.contact, name='contact')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # to import static in deployment
from django.conf.urls.static import static # to import static in deployment

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls',namespace="me")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    sender = forms.EmailField(required=True)
    subject = forms.CharField(max_length=100, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

portfolio/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from .forms import ContactForm

# Create your views here.


def portfolio(request):
    return render(request, 'about_me.html', {})


def cv(request):
    context = {
        "experience": [{
            "name": "Ausbildung zum Fachinformatiker (Anwendungsentwicklung)",
            "place": "SEWOBE AG",
            "placeLink": "https://sewobe.de",
            "time": "August 2017 - Juli 2020",
            "bullets": ["Anpassung und Erweiterung von modularer Cloud-Software",
                        "Verwaltung relationeler Datenbanken",
                        "Entwurf und Umsetzung inovativer Kundenwebseiten (Wordpress)",
                        "Einarbeitung neuer Entwickler",
                        "Individuelle Beratung und Betreuung von Klienten",
                        "Agile Softwareentwicklung",
                        ]
        }, {
            "name": "Praktikum Elektro- und Metaltechnik",
            "place": "IHK Akademie Schwaben",
            "time": "Semptember 2015 - Juli 2016",
            "placeLink": "https://www.ihk-akademie-schwaben.de/",
            "bullets": [
                "Umgang mit CNC-Fräsen und -Drehmaschienen",
                "Aufbau zweckgebundener Platinen",
                "Optimierung von Schaltplänen für Microcontroller",
            ]
        }, {
            "name": "Praktikum Fachinformatiker",
            "place": "XITASO GmbH",
            "time": "März 2013",
            "placeLink": "https://xitaso.com/",
            "bullets": [
                "Erste Grundlagen und Kentnisse im Bereich der angewandten Informatik",
                "Konfiguration von Netzwerkdiensten",
            ]
        }],
        "education": [{
            "name": "Ausbildung zum Anwendungsentwicker",
            "place": "Berufsschule 7 Augsburg",
            "time": "August 2017 - Juli 2020",
            "at": "an der",
            "bullets": [
                "Abschlussprüfungsschnitt: 94 von 100 Punkten (entspricht ca. 1,2)",
            ]
        }, {
            "name": "Fachabitur (Technik)",
            "place": "Fachoberschule Augsburg",
            "time": "Semptember 2015 - Juli 2017",
            "at": "an der"
        }, {
            "name": "Bertolt-Brecht-Realschule",
            "place": "Augsburg",
            "time": "Januar 2014 - Juli 2015",
            "at": "in"
        }, {
            "name": "Jakob-Fugger-Gymnasium",
            "place": "Augsburg",
            "time": "Semptember 2008 - Januar 2014",
            "at": "in"
        }],
        "skills": [
            {"name": "HTML", "stars": 5, },
            {"name": "CSS", "stars": 5, },
            {"name": "JavaScript", "stars": 5, },
            {"name": "TypeScript", "stars": 3, },
            {"name": "PHP", "stars": 5, },
            {"name": "Python", "stars": 3.5, },
            {"name": "SASS/SCSS", "stars": 3.5, },
            {"name": "Java", "stars": 2.5, },
            {"name": "C++", "stars": 2, },
            {"name": "SQL", "stars": 5, }
        ],
        "frameworks": [
            {"name": "Bootstrap", "stars": 4, },
            {"name": "JQuery", "stars": 4.5, },
            {"name": "Angular", "stars": 2.5, },
            {"name": "React", "stars": 2, },
            {"name": "Electron", "stars": 1.5, },
        ],
        "languages": [
            {"name": "Deutsch", "stars": 5, },
            {"name": "Englisch", "stars": 4.5, },
        ],
        "personal": {
            "Stärken": ["Analytisches Denkvermögen", "Teamfähigkeit", "Kompromissbereitschaft", "Flexibilität",
                        "Konfliktfähigkeit", "Kommunikationsfähigkeit", "Empathie",
                        "Qualitätsbewusstsein",  "Ergebnisorientierung"],
            #            "Interessen": ["Programmieren", "Sport"]
        }
    }
    return render(request, 'cv.html', context)

# Create your views here.


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.Post)
        if form.is_valid():
            name = form.cleaned_data['name']
            sender = form.cleaned_data['sender']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            recipients = ['max@asam.dev']

            send_mail("von " + name + " via asam.dev: " +
                      subject, message, sender, recipients)
            form = ContactForm()
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})

portfolio/templates/about_me.html
{% extends "base.html" %}

{% block title %}Über mich{% endblock%}

{% block content %}

<div>
    <h1>Maximilian Asam</h1>
    <hr>
    <p>
        This project is currently on hold. Studying CS comes first.
    </p>
    {% lorem %}
</div>

{% endblock %}

portfolio/templates/base.html
<!DOCTYPE html>

<html lang="de">

<head>
    <title>{% block title %}{% endblock %} - Maximilian Asam</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Description" content="Hallo, mein Name ist Maximilian und ich bin ein heißer Informatiker, der gerne Ananas isst und seinen scheiß Schreibtisch nicht aufräumt.">


    <!-- mine -->
    {% load static %}
    {% load compress %}

    {% compress css inline %}
    <link type="text/x-scss" href="{% static "css/normalize.css" %}" rel="stylesheet">
    <!--<link rel="stylesheet" href="{% static "css/main.css" %}"> -->
    <link type="text/x-scss" href="{% static 'theme.scss' %}" rel="stylesheet">
    {% endcompress %}

    {% compress js inline %}
    <script type="text/javascript" src="{% static "js/main.js" %}"></script>
    {% endcompress %}

    {% load webp %}
    <style>
        #sideNav {
            background-image: url({% webp "img/new-york-night-no-moon.jpg" %});
        }

        .light_mode #sideNav {
            background-image: url({% webp "img/new-york-day.jpg" %});
        }

        .light_mode #sideNav #sideMenu {
            padding: 0 0 60vh 0;
        }
    </style>

    {% block head %}{% endblock %}
</head>

<body {% if request.colorMode %} class="light_mode" {% endif %} onload="startLoad()">

    <div id="loader"></div>


    <div id="sideNav">
        <div id="sideIcon"><i class="material-icons">chevron_right</i></div>
        <div>
            <!--<img id="profilePic" src="{% webp "img/me_resized.jpg" %}" alt="Maximilian Asam">-->
            <h1>Maximilian Asam</h1>
            <div class="sub_header">Full Stack Developer</div>
            <ul id="sideMenu">
                <li>
                    <a href="{% url 'me:home' %}">
                        Über mich
                    </a>
                </li>
                <li>
                    <a href="{% url 'me:curriculum_vitae' %}">
                        Lebenslauf
                    </a>
                </li>
                <li>
                    <a href="{% url 'me:contact' %}">
                        Kontakt
                    </a>
                </li>
            </ul>
        </div>

    </div>

    <div id="topBar">
        <button class="top_bar_element" onclick="toggleColorMode()">
            <i class="material-icons">brightness_3</i>
        </button>
        <button class="top_bar_element" onclick="window.print()">
            <i class="material-icons">print</i>
        </button>
        <button class="top_bar_element" onclick="window.open('mailto:{{request.myMail}}')">
            <i class="material-icons">mail</i>
        </button>
    </div>


    <div id="content">

        <div id="main_wrapper">
            <div id="main">
                {% block content %}{% endblock %}
            </div>
        </div>

        <div id="info_wrapper">
            <div id="infos">
                {% block infos%}{% endblock%}
            </div>
        </div>

    </div>


</body>
<footer>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Quattrocento+Sans" rel="stylesheet">
    <script> </script>
</footer>

</html>

portfolio/templates/contact.html
{% extends "base.html" %}

{% block title %}Kontakt{% endblock %}

{% block content %}

<div>
    <h1>Maximilian Asam</h1>
    <hr>
    <p>
        This doesn't quite work yet. So ... Basically this only deletes your message.
    </p>
    <div class="container">
        <form class="contact_form" action="{{ request.path }}">

            {% csrf_token %}
            {{ form }}

            <input type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

portfolio/templates/cv.html
{% extends "base.html" %}
{% load portfolio_tags %}


{% block title %} Lebenslauf {% endblock %}

{% block head %} {% endblock%}

{% block content %}

<div id="cv">
    <h1 class="with_sub">Maximilian Asam</h1>
    <div class="sub">Full Stack Developer</div>
    <hr>
    <div class="description">
        Hello World!
        Mein Name ist Maximilian und ich bin 22 Jahre alt.
        Ich programmiere seit ich 13 Jahre alt bin und es ist neben meiner Leidenschaft auch zu meinem Beruf geworden.
        Zusätzlich zu meiner Erfahrung in der <i>Webentwicklung</i>, arbeite ich auch an diversen anderen Projekten (z.B. im Bereich des <i>native development</i>).
    </div>
    <div class="stats">
        <div class="stat">
            <div class="stat_link" onclick="window.open('mailto:{{request.myMail}}')">
                <span class="material-icons">email</span> : <span class="desc">{{request.myMail}}</span>
            </div>
        </div>
        <div class="stat"><span class="material-icons">place</span> : <span class="desc">86153 Augsburg, Deutschland</span></div>
        <div class="stat">
            <div class="stat_link" onclick="window.open('{% url 'me:home' %}')">
                <span class="material-icons">home</span> : <span class="desc">asam.dev</span>
            </div>
        </div>
    </div>


    <h2>Erfahrung</h2>
    <hr>
    <div class="experience">
        {% for data in experience %}
        {% include "spotlight.html" %}
        {% endfor %}
    </div>

    <h2>Bildung</h2>
    <hr>
    <div class="education">
        {% for data in education %}
        {% include "spotlight.html" %}
        {% endfor %}
    </div>


    <h2>Persönliches</h2>
    <hr>
    <table class="personal">
        {% for name, line in personal.items %}
        <tr>
            <td class="name">{{name}}</td>
            <td class="points">
                {{ line|join:', ' }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

{% block infos%}

<div id="cvInfos">
    <h2>Skills</h2>
    <hr>
    <table class="skill_list">
        {% for skill in skills|dictsortreversed:"stars" %}
        <tr>
            <td class="skill">{{skill.name}}</td>
            <td class="stars">{% for star in skill.stars|stars %} <span class="material-icons star">{{star}}</span> {% endfor %} </td>
        </tr>
        {% endfor %}
    </table>
    <h2>Frameworks</h2>
    <hr>
    <table class="fw_list">
        {% for framework in frameworks|dictsortreversed:"stars" %}
        <tr>
            <td class="framework">{{framework.name}}</td>
            <td class="stars">{% for star in framework.stars|stars %} <span class="material-icons star">{{star}}</span> {% endfor %} </td>
        </tr>
        {% endfor %}
    </table>
    <h2>Sprachen</h2>
    <hr>
    <table class="lang_list">
        {% for language in languages|dictsortreversed:"stars" %}
        <tr>
            <td class="language">{{language.name}}</td>
            <td class="stars">{% for star in language.stars|stars %} <span class="material-icons star">{{star}}</span> {% endfor %} </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

portfolio/templates/spotlight.html
<div class="spotlight">
    <div class="time tc-soft">{{ data.time }}</div>
    <div class="short tc-soft">
        <span class="tc-normal">{{ data.name }}</span>
        {{ data.at|default:"bei" }}
        <span class="tc-normal">
            {% if data.placeLink %}
            <a class="external" href="{{data.placeLink}}" rel="noopener" target="_blank">
                {{ data.place }}
            </a>
            {% else %}
            {{ data.place }}
            {% endif %}
        </span>
    </div>
    {% if data.bullets %}
    <ul class="bullets">
        {% for bullet in data.bullets %}
        <li>{{ bullet }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>